**Ejercicio 1: Variables y Tipos de Datos Básicos**

•	Contexto: Antes de procesar el DataFrame completo, necesitamos almacenar configuraciones iniciales y constantes para nuestro script de análisis.  

•	Instrucción: Define una variable llamada nombre_empresa con el valor "Bogotá Retail S.A.", una variable tasa_impuesto con el valor 0.19 (float) y una variable activo con el valor True (booleano). Imprime los tres valores junto con su tipo de datos utilizando la función type().

In [16]:
nombre_empresa = ('Bogotá Retail S.A.')
print(nombre_empresa, type(nombre_empresa))

tasa_impuesto = 0.19
print(tasa_impuesto, type(tasa_impuesto))

activo = True
print(activo, type(activo))

Bogotá Retail S.A. <class 'str'>
0.19 <class 'float'>
True <class 'bool'>

**Ejercicio 2: Operadores Aritméticos y Asignación**

•	Contexto: Se requiere calcular de forma manual el valor bruto de una transacción unitaria antes de integrarlo al DataFrame general.  

•	Instrucción: Define dos variables numéricas: precio_unitario = 1500000 y cantidad_unidades = 3. Utiliza operadores aritméticos para calcular el subtotal (precio por cantidad), agrégale un recargo fijo de 25000 por envío mediante el operador de asignación acumulativa (+=), e imprime el resultado final.

In [17]:
precio_unitario = 1500000 
cantidad_unidades = 3
recargo_fijo = 25000

subtotal = precio_unitario * cantidad_unidades
print(subtotal)

4500000

In [18]:
subtotal += recargo_fijo
print(subtotal)

4525000

**Ejercicio 3: Carga del DataFrame con Pandas**  

•	Contexto: El primer paso operativo en cualquier proyecto de datos es importar las fuentes externas y garantizar una lectura estructurada limpia.  

•	Instrucción: Importa pandas as pd. Carga el archivo ventas_bogota_limpiar.csv usando el separador ; y la codificación "latin-1". Guarda el resultado en la variable df y muestra sus dimensiones mediante la propiedad .shape.

In [19]:
import pandas as pd
df = pd.read_csv('ventas_bogota_limpiar.csv', sep = ';', encoding = 'latin-1').shape
df

(205, 9)

**Ejercicio 4: Condicionales Simples (if)**  

•	Contexto: Queremos evaluar dinámicamente el precio del primer producto del dataset para clasificarlo comercialmente.  

•	Instrucción: Extrae el valor del precio de la primera fila (df.loc[0, 'precio']). Utiliza una estructura condicional if-else para evaluar si el precio es mayor a 1,000,000. Si es verdadero, imprime "Producto de gama alta", de lo contrario, imprime "Producto estándar".

In [27]:
precio = df.loc[0, 'precio']

if precio > 1000000:
    print('Producto de gama alta')

else:
    print('Producto estándar')

Producto de gama alta

**Ejercicio 5: Condicionales Múltiples (if-elif-else)**  

•	Contexto: Necesitamos categorizar el volumen de unidades vendidas en la primera transacción del dataset bajo criterios de escala operativa.  

•	Instrucción: Extrae la cantidad de la primera fila (df.loc[0, 'cantidad']). Diseña una estructura condicional múltiple: si la cantidad es mayor o igual a 8, imprime "Venta mayorista"; si está entre 4 y 7, imprime "Venta mediana"; de lo contrario, imprime "Venta minorista".

In [28]:
extraccion_cantidad = df.loc[0, 'cantidad']

if extraccion_cantidad >= 8:
    print('venta mayorista')

elif extraccion_cantidad < 4 and extraccion_cantidad > 7:
    print('venta mediana')

else:
    print('venta minorista')

venta minorista

**Ejercicio 6: Bucle for sobre Series de Pandas**  

•	Contexto: Queremos iterar de forma explícita sobre los primeros elementos de una columna para aplicar una revisión visual rápida.  

•	Instrucción: Utiliza un bucle for para recorrer los primeros 5 elementos de la columna "producto" (df['producto'].head()) e imprime cada nombre de producto precedido por el texto "Artículo registrado: ".

In [29]:
for i in range(len(df["producto"].head())):
     
    print(f'Articulo Regstrado: {df["producto"][i]}')

Articulo Regstrado: Monitor
Articulo Regstrado: Audífonos
Articulo Regstrado: Teclado
Articulo Regstrado: Audífonos
Articulo Regstrado: Audífonos

**Ejercicio 7: Bucle while y Control de Índices**  

•	Contexto: Simularemos el procesamiento iterativo de las primeras filas de nuestro DataFrame utilizando un control de flujo por índice numérico con while.  

•	Instrucción: Inicializa una variable de control i = 0. Utiliza un bucle while para iterar mientras i < 3, imprimiendo el ID de venta y la ciudad correspondiente utilizando df.loc[i, 'id_venta'] y df.loc[i, 'ciudad']. Incrementa el contador en cada iteración.

In [30]:
i = 0

while i < 3:
    print(df.loc[i, 'id_venta'])
    print(df.loc[i, 'ciudad'])

    i = i+1

1
Barranquilla
2
Barranquilla
3
Cali

**Ejercicio 8: Creación de Funciones (def)**  

•	Contexto: Automatizaremos el cálculo del valor total de una venta para reutilizarlo en diferentes procesos de análisis.  

•	Instrucción: Define una función llamada calcular_total(precio, cantidad) que reciba ambos valores como parámetros y retorne el producto de ellos. Pruébala enviando un precio de 250000 y una cantidad de 4, e imprime el resultado.

In [25]:
def calcular_total (precio, cantidad):
    
    return precio * cantidad

resultado = calcular_total(250000, 4)
print(resultado)

1000000

**Ejercicio 9: Manejo de Errores (try-except)
Contexto: Al procesar datos externos o realizar operaciones matemáticas, pueden ocurrir errores imprevistos como divisiones por cero o accesos a índices inexistentes.
Instrucción: Escribe un bloque try-except que intente dividir el primer valor de la columna "precio" entre cero (df.loc[0, 'precio'] / 0). Captura la excepción específica de tipo ZeroDivisionError e imprime un mensaje amigable indicando que la operación no es válida.**

In [26]:
df = pd.read_csv('ventas_bogota_limpiar.csv', sep=';', encoding='utf-8')

try:
    valor = float(df.loc[0, 'precio']) / 0
    print(valor)

except ZeroDivisionError:
    print('la operacion no es valida')

la operacion no es valida

**Ejercicio 10: Inspección Básica del DataFrame**  

•	Contexto: Conocer la estructura de tipos de datos y la presencia de valores nulos es fundamental antes de realizar operaciones de limpieza.  

•	Instrucción: Utiliza el método .info() sobre el DataFrame df para revisar los tipos de datos asignados a cada columna y el conteo de registros no nulos.

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id_venta            205 non-null    int64
 1   fecha               205 non-null    str
 2   producto            205 non-null    str
 3   categoria           205 non-null    str
 4   precio              190 non-null    float64
 5   cantidad            205 non-null    int64
 6   ciudad              196 non-null    str
 7   metodo_pago         163 non-null    str
 8   cliente_satisfecho  163 non-null    str
dtypes: float64(1), int64(2), str(6)
memory usage: 14.5 KB

**Ejercicio 11: Estadísticos Descriptivos Básicos**  

•	Contexto: Necesitamos obtener un panorama general del comportamiento numérico de las columnas cuantitativas.  

•	Instrucción: Ejecuta el método .describe() sobre el DataFrame para visualizar métricas estadísticas clave como media, valores mínimos y máximos de las columnas numéricas.

In [ ]:
df.describe()

         id_venta        precio    cantidad
count  205.000000  1.900000e+02  205.000000
mean    98.365854  1.778548e+06    4.800000
std     58.745361  1.062617e+06    2.616689
min      1.000000  5.276922e+04    1.000000
25%     47.000000  9.050350e+05    2.000000
50%     98.000000  1.806900e+06    5.000000
75%    149.000000  2.662794e+06    7.000000
max    200.000000  3.475482e+06    9.000000

**Ejercicio 12: Selección de Columnas Específicas**  
•	Contexto: Para un análisis financiero enfocado, requerimos aislar un subconjunto de columnas relevantes.  

•	Instrucción: Selecciona las columnas "id_venta", "fecha", "producto" y "precio" del DataFrame principal, guárdalas en un nuevo DataFrame llamado df_financiero y muestra sus primeras 3 filas.

In [ ]:
df

,id_venta,fecha,producto,categoria,precio,cantidad,ciudad,metodo_pago,cliente_satisfecho
0,1,13/02/2024,Monitor,Accesorios,1140503.31,6,Barranquilla,Tarjeta,si
1,2,29/02/2024,Audífonos,Accesorios,2786223.89,2,Barranquilla,NaN,si
2,3,5/04/2024,Teclado,Accesorios,958850.40,3,Cali,NaN,No
3,4,12/05/2024,Audífonos,Periféricos,1544815.40,5,Barranquilla,Efectivo,NaN
4,5,13/05/2024,Audífonos,Periféricos,NaN,9,bogotá,tarjeta,Sí
...,...,...,...,...,...,...,...,...,...
200,11,14/04/2024,Monitor,Periféricos,618930.71,8,bogotá,NaN,NO
201,12,26/02/2024,Teclado,Periféricos,560183.09,1,Bogotá,Tarjeta,si
202,13,29/04/2024,Audífonos,Periféricos,887096.50,6,Medellín,Efectivo,Sí
203,14,23/05/2024,Mouse,Accesorios,1929054.93,1,Cali,tarjeta,si
204,15,4/01/2024,Monitor,Periféricos,2505366.79,2,NaN,Tarjeta,NaN

In [ ]:
df_financiero = df[["id_venta", "fecha", "producto", "precio"]]
df_financiero.head(3)

   id_venta       fecha   producto      precio
0         1  13/02/2024    Monitor  1140503.31
1         2  29/02/2024  Audífonos  2786223.89
2         3   5/04/2024    Teclado   958850.40

**Ejercicio 13: Filtrado de Datos por Condición Simple**  

•	Contexto: El equipo comercial solicita un reporte exclusivo de todas las transacciones realizadas en la ciudad de Cali.  

•	Instrucción: Filtra el DataFrame df para conservar únicamente las filas donde la columna "ciudad" sea igual a "Cali". Guarda el resultado en df_cali y muestra su tamaño mediante .shape.

In [ ]:
df_cali = df[df['ciudad'].str.strip().str.lower() == 'cali']
print(df_cali.shape)

(35, 9)

**Ejercicio 14: Filtrado de Datos con Múltiples Condiciones (&)**  

•	Contexto: Se requiere identificar transacciones de alto valor volumétrico en una categoría específica de productos.  

•	Instrucción: Aplica un filtro combinado sobre df para obtener aquellas filas donde la "cantidad" sea mayor o igual a 5 y la "categoria" sea exactamente "Accesorios". Muestra las primeras 3 filas del resultado.

In [ ]:
filtro = (df['cantidad'] >= 5) & (df['categoria'] == "Accesorios")
resultado = df.loc[filtro, ["cantidad", "categoria"]].head(3)
resultado

    cantidad   categoria
0          6  Accesorios
8          5  Accesorios
26         7  Accesorios

**Ejercicio 15: Creación de Columna Calculada (Venta Total)**  

•	Contexto: El dataset contiene precio unitario y cantidad, pero necesitamos la métrica monetaria total por transacción.  

•	Instrucción: Crea una nueva columna en el DataFrame llamada "venta_total" multiplicando los valores de "precio" por "cantidad". Imprime las primeras 4 filas de las columnas "id_venta", "precio", "cantidad" y "venta_total".

In [31]:
df['venta_total'] = df['precio'] * df['cantidad']

In [ ]:
print(df[["id_venta", "precio", "cantidad", "venta_total"]].head(4))

   id_venta      precio  cantidad  venta_total
0         1  1140503.31         6   6843019.86
1         2  2786223.89         2   5572447.78
2         3   958850.40         3   2876551.20
3         4  1544815.40         5   7724077.00

**Ejercicio 16: Detección de Valores Nulos**  

•	Contexto: Antes de proceder con limpiezas profundas, es indispensable cuantificar los datos faltantes en cada columna.  

•	Instrucción: Utiliza la combinación de métodos .isna().sum() sobre el DataFrame para calcular el número total de valores nulos por columna e imprime el resultado.

In [ ]:
df.isna().sum()

id_venta               0
fecha                  0
producto               0
categoria              0
precio                15
cantidad               0
ciudad                 9
metodo_pago           42
cliente_satisfecho    42
dtype: int64

**Ejercicio 17: Limpieza de Nulos - Imputación Numérica**  

•	Contexto: La columna "precio" contiene valores nulos que pueden alterar cálculos posteriores si no se corrigen.  

•	Instrucción: Calcula el promedio de la columna "precio" usando .mean(). Luego, utiliza ese valor promedio para rellenar los nulos de la misma columna con el método .fillna(). Comprueba que el conteo de nulos en precio sea cero.

In [ ]:
promedio_precio = df['precio'].mean()
df['precio'] = df['precio'].fillna ('promedio_precio')

df['precio'].isna().sum()

np.int64(0)

**Ejercicio 18: Limpieza de Nulos - Relleno de Texto**  

Contexto: Las celdas vacías en columnas categóricas como el método de pago afectan los reportes de segmentación.  

Instrucción: Rellena los valores nulos (NaN) de la columna "metodo_pago" utilizando el texto "No registrado" mediante el método .fillna(). Muestra un conteo de nulos actualizado para esa columna.

In [ ]:
import pandas as pd

df = pd.read_csv('ventas_bogota_limpiar.csv', sep=';', encoding='utf-8')

nulos = df ['metodo_pago'].isna().sum()
df['metodo_pago'] = df['metodo_pago'].fillna('no registrado')
print(f'Cantidad de valores nulos en la columna metodo_pago: {nulos}')

Cantidad de valores nulos en la columna metodo_pago: 42

**Ejercicio 19: Manipulación de Cadenas - Minúsculas y Espacios**  

•	Contexto: Las ciudades presentan variaciones tipográficas (como mayúsculas o espacios adicionales) que deben unificarse.  

•	Instrucción: Utiliza el descriptor .str para transformar todos los textos de la columna "ciudad" a minúsculas y eliminar espacios sobrantes, guardando el resultado en una nueva columna llamada "ciudad_limpia". Muestra las primeras 4 filas.

In [ ]:
df['ciudad_limpia'] = df['ciudad'].str.strip().str.lower()
df['ciudad_limpia'].head(4)

0    barranquilla
1    barranquilla
2            cali
3    barranquilla
Name: ciudad_limpia, dtype: str

**Ejercicio 20: Manipulación de Cadenas - Reemplazo de Textos**  

•	Contexto: Estandarizaremos los nombres de las categorías de productos para asegurar consistencia en los reportes ejecutivos.  

•	Instrucción: Utiliza el método .str.replace() para modificar la columna "categoria", reemplazando cualquier ocurrencia de "Periféricos" por "Perifericos". Muestra una muestra de los datos modificados.

In [ ]:
df['categoria'].str.replace("Periféricos", "Perifericos")

0       Accesorios
1       Accesorios
2       Accesorios
3      Perifericos
4      Perifericos
          ...
200    Perifericos
201    Perifericos
202    Perifericos
203     Accesorios
204    Perifericos
Name: categoria, Length: 205, dtype: str

**Ejercicio 21: Ordenamiento de Datos - Ascendente**  

Contexto: Se requiere listar las transacciones ordenadas de menor a mayor precio unitario para análisis de presupuestos accesibles.  

Instrucción: Ordena el DataFrame en función de la columna "precio" de forma ascendente (ascending=True) utilizando .sort_values(). Muestra las primeras 3 filas del resultado.

In [ ]:
df = pd.read_csv('ventas_bogota_limpiar.csv', sep=';', encoding='utf-8')

df_ordenado = df.sort_values(by='precio', ascending=True).head(10)

df_ordenado

,id_venta,fecha,producto,categoria,precio,cantidad,ciudad,metodo_pago,cliente_satisfecho
100,101,1/05/2024,Monitor,Electrónica,52769.22,8,Cali,tarjeta,No
149,150,2/04/2024,Monitor,Periféricos,54567.45,7,BOGOTA,Efectivo,NaN
163,164,5/03/2024,Laptop,Periféricos,57358.34,2,BOGOTA,NaN,Sí
25,26,18/02/2024,Teclado,Electrónica,65161.31,5,Bogotá,Transferencia,Sí
64,65,7/03/2024,Mouse,Accesorios,78503.06,2,Barranquilla,Efectivo,No
70,71,30/03/2024,Laptop,Accesorios,96102.70,2,Medellín,Tarjeta,Sí
5,6,15/06/2024,Mouse,Electrónica,103347.34,2,bogotá,Tarjeta,No
49,50,23/05/2024,Monitor,Electrónica,107391.92,8,Medellín,Tarjeta,Sí
28,29,26/04/2024,Monitor,Periféricos,156939.88,1,Barranquilla,Tarjeta,No
165,166,12/02/2024,Mouse,Accesorios,165412.29,6,Cali,Efectivo,Sí

**Ejercicio 22: Ordenamiento de Datos - Descendente**  

•	Contexto: La gerencia necesita identificar de inmediato las transacciones comerciales que generaron mayor ingreso total.  

•	Instrucción: Asegúrate de tener calculada la columna "venta_total" y ordena el DataFrame de forma descendente (ascending=False) usando .sort_values(). Muestra las 3 transacciones principales.

In [32]:
df['venta_total'] = df['precio'] * df['cantidad']
top_3 = df.sort_values(by='venta_total', ascending=False).head(3)
top_3

,id_venta,fecha,producto,categoria,precio,cantidad,ciudad,metodo_pago,cliente_satisfecho,venta_total
171,172,6/05/2024,Laptop,Electrónica,3393019.34,9,bogotá,Tarjeta,Sí,30537174.06
162,163,16/03/2024,Audífonos,Periféricos,3371830.55,9,Cali,Tarjeta,No,30346474.95
59,60,16/04/2024,Mouse,Electrónica,3364749.11,9,NaN,NaN,si,30282741.99

**Ejercicio 23: Agrupamiento Simple (groupby)**  

•	Contexto: Necesitamos conocer la cantidad total de unidades vendidas agrupadas por cada categoría de producto.  

•	Instrucción: Utiliza .groupby("categoria") combinado con la función de agregación .sum() sobre la columna "cantidad" para obtener el total de unidades por categoría. Muestra el resultado.

In [ ]:
unidades_vendidas = df.groupby('categoria')['cantidad'].sum()
unidades_vendidas

categoria
Accesorios     320
Electrónica    318
Periféricos    346
Name: cantidad, dtype: int64

**Ejercicio 24: Agregaciones Múltiples con .agg()**  

•	Contexto: El departamento financiero requiere un reporte avanzado que detalle simultáneamente el ingreso total y el precio promedio por categoría.  

•	Instrucción: Agrupa el DataFrame por "categoria" y utiliza el método .agg() para calcular la suma de "venta_total" y el promedio de "precio". Restablece el índice con .reset_index() y muestra la tabla resultante.

In [ ]:
departamento_financiero = df.groupby('categoria').agg(
    venta_total = ('venta_total', 'sum'), 
    valor = ('precio', 'mean'))

departamento_financiero = departamento_financiero.reset_index()
departamento_financiero

     categoria   venta_total         valor
0   Accesorios  5.482465e+08  1.902572e+06
1  Electrónica  5.329718e+08  1.741464e+06
2  Periféricos  5.633076e+08  1.690330e+06

**Ejercicio 25: Función Personalizada Aplicada al DataFrame (def + iteración/apply)**  

•	Contexto: Queremos clasificar cada transacción con una etiqueta de costo utilizando una función lógica personalizada.  
•	Instrucción: Define una función llamada etiquetar_precio(precio) que retorne "Alto" si el precio es mayor a 1,500,000 y "Normal" en caso contrario. Utiliza un bucle for o aplica la lógica para mostrar la etiqueta de las primeras 5 filas de precios.

In [34]:
# FUNCION:

def etiquetar_precio(precio):
    if precio > 1500000:
        return "Alto"
    else:
        return "Normal"

# CREAMOS UNA LISTA VACIA:

precios = []

# PEDIMOS LOS 5 PRECIOS Y CADA QUE EL CLIENTE LOS INGRESE, SE ALMACENAN EN LA LISTA VACIA:

for i in range(5):
    precio = int(input("Ingrese el precio: "))
    precios.append(precio)

# AHORA SE CLASIFICAN LOS 5 PRECIOS:

for precio in precios:
    print("Precio:", precio, "-", etiquetar_precio(precio))

Precio: 20000 - Normal
Precio: 2345 - Normal
Precio: 10000000000000 - Alto
Precio: 200000000000 - Alto
Precio: 34560000 - Alto

**Ejercicio 26: Filtrado con método .isin()
Contexto: Queremos aislar registros que pertenezcan exclusivamente a un conjunto específico de ciudades clave.
Instrucción: Utiliza el método .isin(["Bogotá", "Cali"]) sobre la columna "ciudad" para filtrar el DataFrame y conservar únicamente las transacciones de estas dos ciudades. Muestra el número total de registros coincidentes.**

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('ventas_bogota_limpiar.csv')

In [ ]:
df = pd.read_csv('ventas_bogota_limpiar.csv', sep=';', encoding='utf-8')

In [ ]:
df

,id_venta,fecha,producto,categoria,precio,cantidad,ciudad,metodo_pago,cliente_satisfecho
0,1,13/02/2024,Monitor,Accesorios,1140503.31,6,Barranquilla,Tarjeta,si
1,2,29/02/2024,Audífonos,Accesorios,2786223.89,2,Barranquilla,NaN,si
2,3,5/04/2024,Teclado,Accesorios,958850.40,3,Cali,NaN,No
3,4,12/05/2024,Audífonos,Periféricos,1544815.40,5,Barranquilla,Efectivo,NaN
4,5,13/05/2024,Audífonos,Periféricos,NaN,9,bogotá,tarjeta,Sí
...,...,...,...,...,...,...,...,...,...
200,11,14/04/2024,Monitor,Periféricos,618930.71,8,bogotá,NaN,NO
201,12,26/02/2024,Teclado,Periféricos,560183.09,1,Bogotá,Tarjeta,si
202,13,29/04/2024,Audífonos,Periféricos,887096.50,6,Medellín,Efectivo,Sí
203,14,23/05/2024,Mouse,Accesorios,1929054.93,1,Cali,tarjeta,si
204,15,4/01/2024,Monitor,Periféricos,2505366.79,2,NaN,Tarjeta,NaN

In [ ]:
ciudades_clave = df[df['ciudad'].isin(['Bogotá', 'Cali'])]

In [ ]:
ciudades_clave.groupby('ciudad')['precio'].sum()

ciudad
Bogotá    58157023.17
Cali      59727204.18
Name: precio, dtype: float64

**Ejercicio 27: Combinación de Datos - Cruce Relacional (pd.merge)
Contexto: Integraremos una tabla externa con tasas de bonificación comercial basadas en el método de pago utilizado.
Instrucción: Crea un DataFrame secundario con las columnas "metodo_pago" (ej. "Tarjeta", "Efectivo", "Transferencia") y "bonificacion" (ej. [0.05, 0.02, 0.03]). Realiza un cruce relacional tipo left join (pd.merge) utilizando la columna en común. Muestra las primeras 4 filas del resultado.**

In [ ]:
import pandas as pd

In [ ]:
df_nuevo = pd.DataFrame(
    {
        'metodo_pago': ["Tarjeta", "Efectivo", "Transferencia"],
        'bonificacion': [0.05, 0.02, 0.03]
    }
)
df_nuevo

     metodo_pago  bonificacion
0        Tarjeta          0.05
1       Efectivo          0.02
2  Transferencia          0.03

In [ ]:
# union usando df.merge direccion .left

df_join = pd.merge(df , df_nuevo, on = 'metodo_pago', how = 'left')
df_join

,id_venta,fecha,producto,categoria,precio,cantidad,ciudad,metodo_pago,cliente_satisfecho,bonificacion
0,1,13/02/2024,Monitor,Accesorios,1140503.31,6,Barranquilla,Tarjeta,si,0.05
1,2,29/02/2024,Audífonos,Accesorios,2786223.89,2,Barranquilla,NaN,si,NaN
2,3,5/04/2024,Teclado,Accesorios,958850.40,3,Cali,NaN,No,NaN
3,4,12/05/2024,Audífonos,Periféricos,1544815.40,5,Barranquilla,Efectivo,NaN,0.02
4,5,13/05/2024,Audífonos,Periféricos,NaN,9,bogotá,tarjeta,Sí,NaN
...,...,...,...,...,...,...,...,...,...,...
200,11,14/04/2024,Monitor,Periféricos,618930.71,8,bogotá,NaN,NO,NaN
201,12,26/02/2024,Teclado,Periféricos,560183.09,1,Bogotá,Tarjeta,si,0.05
202,13,29/04/2024,Audífonos,Periféricos,887096.50,6,Medellín,Efectivo,Sí,0.02
203,14,23/05/2024,Mouse,Accesorios,1929054.93,1,Cali,tarjeta,si,NaN
204,15,4/01/2024,Monitor,Periféricos,2505366.79,2,NaN,Tarjeta,NaN,0.05

In [ ]:
df = pd.read_csv('ventas_bogota_limpiar.csv', sep=';', encoding='utf-8')

df

,id_venta,fecha,producto,categoria,precio,cantidad,ciudad,metodo_pago,cliente_satisfecho
0,1,13/02/2024,Monitor,Accesorios,1140503.31,6,Barranquilla,Tarjeta,si
1,2,29/02/2024,Audífonos,Accesorios,2786223.89,2,Barranquilla,NaN,si
2,3,5/04/2024,Teclado,Accesorios,958850.40,3,Cali,NaN,No
3,4,12/05/2024,Audífonos,Periféricos,1544815.40,5,Barranquilla,Efectivo,NaN
4,5,13/05/2024,Audífonos,Periféricos,NaN,9,bogotá,tarjeta,Sí
...,...,...,...,...,...,...,...,...,...
200,11,14/04/2024,Monitor,Periféricos,618930.71,8,bogotá,NaN,NO
201,12,26/02/2024,Teclado,Periféricos,560183.09,1,Bogotá,Tarjeta,si
202,13,29/04/2024,Audífonos,Periféricos,887096.50,6,Medellín,Efectivo,Sí
203,14,23/05/2024,Mouse,Accesorios,1929054.93,1,Cali,tarjeta,si
204,15,4/01/2024,Monitor,Periféricos,2505366.79,2,NaN,Tarjeta,NaN

**Ejercicio 28: Uso de Bloque try-except para Conversión de Tipos**  

•	Contexto: Al transformar columnas de texto numérico a formato flotante o entero, pueden surgir errores por caracteres inesperados.  

•	Instrucción: Escribe un bloque try-except que intente convertir una columna de texto arbitraria a entero mediante pd.to_numeric(..., errors='raise'). Si ocurre una excepción (ej. ValueError), captura el error e imprímelo informando de la anomalía de formato.

In [ ]:
try:
    # 1. Se ejecuta directamente pd.to_numeric con el texto arbitrario
    saludo = pd.to_numeric('hola', errors='raise')
    
except ValueError:
    # 2. Como 'errors=raise', pd.to_numeric lanzará el ValueError aquí
    print('no es posible convertir texto a numero (anomalía de formato)')

no es posible convertir texto a numero (anomalía de formato)

**Ejercicio 29: Agrupamiento con Múltiples Dimensiones**  

•	Contexto: Necesitamos refinar nuestro análisis segmentando los datos tanto por ciudad como por categoría de producto de manera simultánea.  

•	Instrucción: Agrupa el DataFrame utilizando una lista de columnas ["ciudad", "categoria"] y calcula el promedio de la columna "precio" mediante .mean(). Restablece el índice e imprime las primeras 5 filas.

In [ ]:
analisis = df.groupby(['ciudad', 'categoria'])['precio'].mean().reset_index().head()
analisis

         ciudad    categoria        precio
0        BOGOTA   Accesorios  1.696480e+06
1        BOGOTA  Electrónica  1.687677e+06
2        BOGOTA  Periféricos  1.432998e+06
3  Barranquilla   Accesorios  1.613938e+06
4  Barranquilla  Electrónica  1.202050e+06

**Ejercicio 30: Consolidación y Resumen Final con Funciones y Bucles**  

•	Contexto: Crearemos un bloque de script que combine lógica de funciones personalizadas y bucles para resumir estadísticas clave del dataset limpio.  

•	Instrucción: Define una función que reciba un DataFrame y devuelva el ingreso total acumulado ("venta_total"). Utiliza un bucle for para iterar sobre las ciudades únicas del DataFrame, imprimiendo el ingreso total generado en cada ciudad específica calculado mediante un filtro dinámico.

In [35]:
def calcular_ingreso_total(df_filtrado):
    # Sumamos los valores de la columna "venta_total"
    ingreso_total = df_filtrado['venta_total'].sum()
    return ingreso_total

# Esto nos da una lista con los nombres de cada ciudad única
ciudades_unicas = df['ciudad'].unique()

# Iteramos sobre cada ciudad de la lista
for ciudad in ciudades_unicas:
    # FILTRO DINÁMICO: Seleccionamos solo las filas de la ciudad actual
    df_ciudad = df[df['ciudad'] == ciudad]
    
    # LLAMADA A LA FUNCIÓN: Calculamos el ingreso total de esa ciudad
    total_ciudad = calcular_ingreso_total(df_ciudad)
    
    # IMPRESIÓN: Mostramos el resultado en pantalla
    print(f"El ingreso total generado en la ciudad de {ciudad} es: ${total_ciudad:.2f}")

El ingreso total generado en la ciudad de Barranquilla es: $266213358.58
El ingreso total generado en la ciudad de Cali es: $239381108.04
El ingreso total generado en la ciudad de bogotá es: $307023831.08
El ingreso total generado en la ciudad de Bogotá es: $258503453.10
El ingreso total generado en la ciudad de Medellín es: $245306507.36
El ingreso total generado en la ciudad de BOGOTA es: $220489752.05
El ingreso total generado en la ciudad de nan es: $0.00