**Ejercicio 1: Carga e Inspección Básica del Archivo CSV**

•	Contexto: El primer paso para cualquier análisis de datos profesional es importar correctamente nuestra fuente y evaluar su salud estructural (dimensiones, columnas y nulos).  

•	Instrucción: Importa la librería pandas as pd. Lee el archivo ventas_bogota_limpiar.csv asegurándote de usar el parámetro de separación correcto (sep=";"), ya que el archivo está estructurado con punto y coma. Guarda el resultado en un DataFrame llamado df y muestra sus primeras 5 filas con .head() y un resumen técnico con .info().

In [2]:
import pandas as pd

In [7]:
df = pd.read_csv('ventas_bogota_limpiar.csv', sep = ';')
df.head()

,id_venta,fecha,producto,categoria,precio,cantidad,ciudad,metodo_pago,cliente_satisfecho
0,1,13/02/2024,Monitor,Accesorios,1140503.31,6,Barranquilla,Tarjeta,si
1,2,29/02/2024,Audífonos,Accesorios,2786223.89,2,Barranquilla,NaN,si
2,3,5/04/2024,Teclado,Accesorios,958850.40,3,Cali,NaN,No
3,4,12/05/2024,Audífonos,Periféricos,1544815.40,5,Barranquilla,Efectivo,NaN
4,5,13/05/2024,Audífonos,Periféricos,NaN,9,bogotá,tarjeta,Sí

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id_venta            205 non-null    int64
 1   fecha               205 non-null    str
 2   producto            205 non-null    str
 3   categoria           205 non-null    str
 4   precio              190 non-null    float64
 5   cantidad            205 non-null    int64
 6   ciudad              196 non-null    str
 7   metodo_pago         163 non-null    str
 8   cliente_satisfecho  163 non-null    str
dtypes: float64(1), int64(2), str(6)
memory usage: 14.5 KB

**Ejercicio 2: Inspección Estadística y Estadísticos Descriptivos**

•	Contexto: Antes de limpiar, necesitamos conocer el comportamiento numérico general de nuestras métricas de negocio para identificar posibles anomalías.  

•	Instrucción: Utiliza el método .describe() sobre tu DataFrame df para obtener las estadísticas clave (promedio, valores mínimos, máximos y desviación estándar) de las columnas numéricas. Adicionalmente, imprime cuántos valores nulos totales existen en cada columna utilizando la combinación de .isna().sum().

In [ ]:
df.describe() # muestra estadisticas descriptivas de las columnas numericas

         id_venta        precio    cantidad
count  205.000000  1.900000e+02  205.000000
mean    98.365854  1.778548e+06    4.800000
std     58.745361  1.062617e+06    2.616689
min      1.000000  5.276922e+04    1.000000
25%     47.000000  9.050350e+05    2.000000
50%     98.000000  1.806900e+06    5.000000
75%    149.000000  2.662794e+06    7.000000
max    200.000000  3.475482e+06    9.000000

In [ ]:
df.isna().sum() # cuenta los valores nulos por columna

id_venta               0
fecha                  0
producto               0
categoria              0
precio                15
cantidad               0
ciudad                 9
metodo_pago           42
cliente_satisfecho    42
dtype: int64

**Ejercicio 4: Filtrado Condicional de Registros**

•	Contexto: La gerencia te solicita aislar exclusivamente aquellas transacciones comerciales en donde la cantidad de unidades vendidas sea mayor o igual a 8.  

•	Instrucción: Aplica un filtro condicional sobre el DataFrame principal para conservar solo las filas donde la columna "cantidad" sea >= 8. Guarda este resultado en df_volumen y muestra cuántas transacciones cumplieron con esta condición usando la propiedad .shape.

In [14]:
df

,id_venta,fecha,producto,categoria,precio,cantidad,ciudad,metodo_pago,cliente_satisfecho
0,1,13/02/2024,Monitor,Accesorios,1140503.31,6,Barranquilla,Tarjeta,si
1,2,29/02/2024,Audífonos,Accesorios,2786223.89,2,Barranquilla,NaN,si
2,3,5/04/2024,Teclado,Accesorios,958850.40,3,Cali,NaN,No
3,4,12/05/2024,Audífonos,Periféricos,1544815.40,5,Barranquilla,Efectivo,NaN
4,5,13/05/2024,Audífonos,Periféricos,NaN,9,bogotá,tarjeta,Sí
...,...,...,...,...,...,...,...,...,...
200,11,14/04/2024,Monitor,Periféricos,618930.71,8,bogotá,NaN,NO
201,12,26/02/2024,Teclado,Periféricos,560183.09,1,Bogotá,Tarjeta,si
202,13,29/04/2024,Audífonos,Periféricos,887096.50,6,Medellín,Efectivo,Sí
203,14,23/05/2024,Mouse,Accesorios,1929054.93,1,Cali,tarjeta,si
204,15,4/01/2024,Monitor,Periféricos,2505366.79,2,NaN,Tarjeta,NaN

In [28]:
df_volumen = df[df['cantidad'] >= 8].shape[0] # cuenta el numero de filas que cumplen la condicion
print(f'{df_volumen} transacciones cumplen con esta condicion')

42 transacciones cumplen con esta condicion

**Ejercicio 5: Creación de una Columna Calculada (Venta Total)**

•	Contexto: El dataset cuenta con el precio unitario y las unidades vendidas, pero carece de la columna que arroje el valor monetario total de cada transacción.  

•	Instrucción: Crea una nueva columna en tu DataFrame llamada "venta_total" multiplicando la columna "precio" por la columna "cantidad". Luego, muestra las primeras 5 filas de las columnas "id_venta", "precio", "cantidad" y "venta_total" para validar el cálculo.

In [32]:
df['venta_total'] = df['precio'] * df['cantidad']

In [36]:
df[['id_venta', 'precio', 'cantidad', 'venta_total']].head()

   id_venta      precio  cantidad  venta_total
0         1  1140503.31         6   6843019.86
1         2  2786223.89         2   5572447.78
2         3   958850.40         3   2876551.20
3         4  1544815.40         5   7724077.00
4         5         NaN         9          NaN

**Ejercicio 6: Limpieza de Valores Nulos (Imputación por Promedio)**

•	Contexto: Como viste en la inspección del Ejercicio 2, la columna "precio" contiene 15 valores nulos (NaN) que podrían corromper nuestros análisis financieros si no se tratan adecuadamente.  

•	Instrucción: Calcula el promedio de la columna "precio" utilizando .mean(). Posteriormente, utiliza ese valor promedio para rellenar los espacios vacíos (NaN) de esa misma columna usando el método .fillna(). Comprueba que el número de nulos en "precio" sea 0 después de la operación.

In [ ]:
precio_promedio = df['precio'].mean() # calcula el promedio de la columna precio

In [38]:
df['precio'] = df['precio'].fillna(precio_promedio) # reemplaza los valores nulos de la columna precio con el promedio

In [39]:
df['precio'].isna().sum() # comprueba que ya no hay nulos

np.int64(0)

**Ejercicio 7: Filtrado Combinado con Múltiples Condiciones Lógicas**

•	Contexto: El departamento de análisis de mercado necesita perfilar un grupo específico de transacciones de alto valor y volumen en zonas clave.  

•	Instrucción: Filtra el DataFrame para obtener únicamente aquellas transacciones donde la "cantidad" sea mayor a 5 y la categoría del producto sea exactamente "Accesorios" (puedes usar el operador lógico & y paréntesis para separar las condiciones). Muestra el número total de registros coincidentes.

In [44]:
df_volumen = df[(df['cantidad'] > 5) & (df['categoria'] == 'Accesorios')].shape[0] # cuenta el numero de filas que cumplen la condicion
print(f'{df_volumen} es el numero total de registros coincidentes')

26 es el numero total de registros coincidentes